In [431]:
import keras

In [432]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [433]:
data=pd.read_csv("C:/Users/Anubhav Sanyal/Desktop/Deep Leaning/Artificial_Neural_Networks/Churn_Modelling.csv")

In [434]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [435]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [436]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...
9970,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [437]:
data.Geography[data.Geography=="France"]=1
data.Geography[data.Geography=="Spain"]=2
data.Geography[data.Geography=="Germany"]=3

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [438]:
data.Gender[data.Gender=="Female"]=0
data.Gender[data.Gender=="Male"]=1

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [439]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,1,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,1,0,42,8,159660.80,3,1,0,113931.57,1
3,699,1,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
5,645,2,1,44,8,113755.78,2,1,0,149756.71,1
6,822,1,1,50,7,0.00,2,1,1,10062.80,0
7,376,3,0,29,4,115046.74,4,1,0,119346.88,1
8,501,1,1,44,4,142051.07,2,0,1,74940.50,0
9,684,1,1,27,2,134603.88,1,1,1,71725.73,0
10,528,1,1,31,6,102016.72,2,0,0,80181.12,0
11,497,2,1,24,3,0.00,2,1,0,76390.01,0
12,476,1,0,34,10,0.00,2,1,0,26260.98,0
13,549,1,0,25,5,0.00,2,0,0,190857.79,0
14,635,2,0,35,7,0.00,2,1,1,65951.65,0
15,616,3,1,45,3,143129.41,2,0,1,64327.26,0
16,653,3,1,58,1,132602.88,1,1,0,5097.67,1
17,549,2,0,24,9,0.00,2,1,1,14406.41,0
18,587,2,1,45,6,0.00,1,0,0,158684.81,0
19,726,1,0,24,6,0.00,2,1,1,54724.03,0
20,732,1,1,41,8,0.00,2,1,1,170886.17,0
21,636,2,0,32,8,0.00,2,1,0,138555.46,0
22,510,2,0,38,4,0.00,1,1,0,118913.53,1
23,669,1,1,46,3,0.00,2,0,1,8487.75,0
24,846,1,0,38,5,0.00,1,1,1,187616.16,0
25,577,1,1,25,3,0.00,2,0,1,124508.29,0
26,756,3,1,36,2,136815.64,1,1,1,170041.95,0
27,571,1,1,44,9,0.00,2,0,0,38433.35,0
28,574,3,0,43,3,141349.43,1,1,1,100187.43,0
29,411,1,1,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...
9970,518,1,1,42,7,151027.05,2,1,0,119377.36,0
9971,833,1,0,34,3,144751.81,1,0,0,166472.81,0
9972,758,1,1,26,4,155739.76,1,1,0,171552.02,0
9973,611,1,1,27,7,0.00,2,1,1,157474.10,0
9974,583,1,1,33,7,122531.86,1,1,0,13549.24,0
9975,610,3,1,50,1,113957.01,2,1,0,196526.55,1
9976,637,1,0,33,7,103377.81,1,1,0,84419.78,0
9977,683,1,0,32,9,0.00,2,1,1,24991.92,0
9978,774,1,1,40,9,93017.47,2,1,0,191608.97,0
9979,677,1,0,58,1,90022.85,1,0,1,2988.28,0
9980,741,2,1,35,6,74371.49,1,0,0,99595.67,0
9981,498,3,1,42,3,152039.70,1,1,1,53445.17,1
9982,655,3,0,46,7,137145.12,1,1,0,115146.40,1
9983,613,1,1,40,4,0.00,1,0,0,151325.24,0
9984,602,3,1,35,7,90602.42,2,1,1,51695.41,0
9985,659,1,1,36,6,123841.49,2,1,0,96833.00,0
9986,673,3,1,47,1,183579.54,2,0,1,34047.54,0
9987,606,2,1,30,8,180307.73,2,1,1,1914.41,0
9988,775,1,1,30,4,0.00,2,1,0,49337.84,0
9989,841,2,1,28,4,0.00,2,1,1,179436.60,0
9990,714,3,1,33,3,35016.60,1,1,0,53667.08,0
9991,597,1,0,53,4,88381.21,1,1,0,69384.71,1
9992,726,2,1,36,2,0.00,1,1,0,195192.40,0
9993,644,1,1,28,7,155060.41,1,1,0,29179.52,0
9994,800,1,0,29,2,0.00,2,0,0,167773.55,0
9995,771,1,1,39,5,0.00,2,1,0,96270.64,0
9996,516,1,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,1,0,36,7,0.00,1,0,1,42085.58,1
9998,772,3,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,1,0,28,4,130142.79,1,1,0,38190.78,0

In [440]:
X=data.iloc[:,0:10]

In [441]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,1,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,1,0,42,8,159660.80,3,1,0,113931.57
3,699,1,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
5,645,2,1,44,8,113755.78,2,1,0,149756.71
6,822,1,1,50,7,0.00,2,1,1,10062.80
7,376,3,0,29,4,115046.74,4,1,0,119346.88
8,501,1,1,44,4,142051.07,2,0,1,74940.50
9,684,1,1,27,2,134603.88,1,1,1,71725.73
10,528,1,1,31,6,102016.72,2,0,0,80181.12
11,497,2,1,24,3,0.00,2,1,0,76390.01
12,476,1,0,34,10,0.00,2,1,0,26260.98
13,549,1,0,25,5,0.00,2,0,0,190857.79
14,635,2,0,35,7,0.00,2,1,1,65951.65
15,616,3,1,45,3,143129.41,2,0,1,64327.26
16,653,3,1,58,1,132602.88,1,1,0,5097.67
17,549,2,0,24,9,0.00,2,1,1,14406.41
18,587,2,1,45,6,0.00,1,0,0,158684.81
19,726,1,0,24,6,0.00,2,1,1,54724.03
20,732,1,1,41,8,0.00,2,1,1,170886.17
21,636,2,0,32,8,0.00,2,1,0,138555.46
22,510,2,0,38,4,0.00,1,1,0,118913.53
23,669,1,1,46,3,0.00,2,0,1,8487.75
24,846,1,0,38,5,0.00,1,1,1,187616.16
25,577,1,1,25,3,0.00,2,0,1,124508.29
26,756,3,1,36,2,136815.64,1,1,1,170041.95
27,571,1,1,44,9,0.00,2,0,0,38433.35
28,574,3,0,43,3,141349.43,1,1,1,100187.43
29,411,1,1,29,0,59697.17,2,1,1,53483.21
...,...,...,...,...,...,...,...,...,...,...
9970,518,1,1,42,7,151027.05,2,1,0,119377.36
9971,833,1,0,34,3,144751.81,1,0,0,166472.81
9972,758,1,1,26,4,155739.76,1,1,0,171552.02
9973,611,1,1,27,7,0.00,2,1,1,157474.10
9974,583,1,1,33,7,122531.86,1,1,0,13549.24
9975,610,3,1,50,1,113957.01,2,1,0,196526.55
9976,637,1,0,33,7,103377.81,1,1,0,84419.78
9977,683,1,0,32,9,0.00,2,1,1,24991.92
9978,774,1,1,40,9,93017.47,2,1,0,191608.97
9979,677,1,0,58,1,90022.85,1,0,1,2988.28
9980,741,2,1,35,6,74371.49,1,0,0,99595.67
9981,498,3,1,42,3,152039.70,1,1,1,53445.17
9982,655,3,0,46,7,137145.12,1,1,0,115146.40
9983,613,1,1,40,4,0.00,1,0,0,151325.24
9984,602,3,1,35,7,90602.42,2,1,1,51695.41
9985,659,1,1,36,6,123841.49,2,1,0,96833.00
9986,673,3,1,47,1,183579.54,2,0,1,34047.54
9987,606,2,1,30,8,180307.73,2,1,1,1914.41
9988,775,1,1,30,4,0.00,2,1,0,49337.84
9989,841,2,1,28,4,0.00,2,1,1,179436.60
9990,714,3,1,33,3,35016.60,1,1,0,53667.08
9991,597,1,0,53,4,88381.21,1,1,0,69384.71
9992,726,2,1,36,2,0.00,1,1,0,195192.40
9993,644,1,1,28,7,155060.41,1,1,0,29179.52
9994,800,1,0,29,2,0.00,2,0,0,167773.55
9995,771,1,1,39,5,0.00,2,1,0,96270.64
9996,516,1,1,35,10,57369.61,1,1,1,101699.77
9997,709,1,0,36,7,0.00,1,0,1,42085.58
9998,772,3,1,42,3,75075.31,2,1,0,92888.52
9999,792,1,0,28,4,130142.79,1,1,0,38190.78

In [442]:
y=data.iloc[:,10]

In [443]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [392]:
X=X.values

In [393]:
y=y.values

In [444]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=100)

In [445]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [368]:
X=X.values
y=y.values

In [446]:
from keras.models import Sequential

In [447]:
from keras.layers import Dense

In [448]:
classifier=Sequential()

In [449]:
classifier.add(Dense(units=6,init="uniform",activation="relu",input_dim=10))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", input_dim=10, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [450]:
classifier.add(Dense(output_dim=6,init="uniform",activation="relu"))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [451]:
classifier.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.

In [452]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [453]:
classifier.fit(X_train,y_train,batch_size=32,nb_epoch=55)

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.

Epoch 1/55
8000/8000 [==============================] - 4s 489us/step - loss: 0.5849 - acc: 0.7969
Epoch 2/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.4367 - acc: 0.7969
Epoch 3/55
8000/8000 [==============================] - 1s 118us/step - loss: 0.4280 - acc: 0.7969
Epoch 4/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.4235 - acc: 0.7969
Epoch 5/55
8000/8000 [==============================] - 1s 117us/step - loss: 0.4183 - acc: 0.8177
Epoch 6/55
8000/8000 [==============================] - 1s 128us/step - loss: 0.4124 - acc: 0.8346
Epoch 7/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.4082 - acc: 0.8346
Epoch 8/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.4050 - acc: 0.8356
Epoch 9/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.4027 - acc: 0.8359
Epoch 10/55
8000/8000 [==============================] - 1s 127us/step - loss: 0.4011 - acc: 0.8356 1s - loss: 0
Epoch 11/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.4000 - acc: 0.8370
Epoch 12/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.3988 - acc: 0.8357
Epoch 13/55
8000/8000 [==============================] - 1s 114us/step - loss: 0.3976 - acc: 0.8380
Epoch 14/55
8000/8000 [==============================] - 1s 113us/step - loss: 0.3975 - acc: 0.8381
Epoch 15/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.3967 - acc: 0.8377
Epoch 16/55
8000/8000 [==============================] - 1s 124us/step - loss: 0.3959 - acc: 0.8373
Epoch 17/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.3956 - acc: 0.8371
Epoch 18/55
8000/8000 [==============================] - 1s 117us/step - loss: 0.3949 - acc: 0.8376
Epoch 19/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.3948 - acc: 0.8384
Epoch 20/55
8000/8000 [==============================] - 1s 118us/step - loss: 0.3946 - acc: 0.8365
Epoch 21/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.3939 - acc: 0.8371
Epoch 22/55
8000/8000 [==============================] - 1s 109us/step - loss: 0.3939 - acc: 0.8371
Epoch 23/55
8000/8000 [==============================] - 1s 119us/step - loss: 0.3938 - acc: 0.8381
Epoch 24/55
8000/8000 [==============================] - 1s 128us/step - loss: 0.3933 - acc: 0.8359
Epoch 25/55
8000/8000 [==============================] - 1s 124us/step - loss: 0.3933 - acc: 0.8386
Epoch 26/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.3932 - acc: 0.8382
Epoch 27/55
8000/8000 [==============================] - 1s 125us/step - loss: 0.3927 - acc: 0.8381
Epoch 28/55
8000/8000 [==============================] - 1s 119us/step - loss: 0.3927 - acc: 0.8376
Epoch 29/55
8000/8000 [==============================] - 1s 126us/step - loss: 0.3921 - acc: 0.8386
Epoch 30/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.3926 - acc: 0.8371
Epoch 31/55
8000/8000 [==============================] - 1s 124us/step - loss: 0.3924 - acc: 0.8382 0s - loss: 0.
Epoch 32/55
8000/8000 [==============================] - 1s 123us/step - loss: 0.3926 - acc: 0.8381
Epoch 33/55
8000/8000 [==============================] - 1s 124us/step - loss: 0.3922 - acc: 0.8364
Epoch 34/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.3921 - acc: 0.8375
Epoch 35/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.3917 - acc: 0.8394 1s - loss: 0.4
Epoch 36/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.3917 - acc: 0.8373
Epoch 37/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.3914 - acc: 0.8369
Epoch 38/55
8000/8000 [==============================] - 1s 116us/step - loss: 0.3911 - acc: 0.8385
Epoch 39/55
8000/8000 [==============================] - 1s 119us/step - loss: 0.3909 - acc: 0.8380
Epoch 40/55
8000/8000 [==============================] - 1s 118us/step - loss: 0.3907 - acc: 0.8386
Epoch 41/55
8000/8000 [==============================] - 1s 119us/step - loss: 0.3898 - acc: 0.8386
Epoch 42/55
8000/8000 [==============================] - 1s 131us/step - loss: 0.3889 - acc: 0.8384
Epoch 43/55
8000/8000 [==============================] - 1s 134us/step - loss: 0.3880 - acc: 0.8392
Epoch 44/55
8000/8000 [==============================] - 1s 124us/step - loss: 0.3865 - acc: 0.8382
Epoch 45/55
8000/8000 [==============================] - 1s 119us/step - loss: 0.3850 - acc: 0.8392
Epoch 46/55
8000/8000 [==============================] - 1s 125us/step - loss: 0.3832 - acc: 0.8402
Epoch 47/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.3813 - acc: 0.8399 1s - loss: 0.
Epoch 48/55
8000/8000 [==============================] - 1s 125us/step - loss: 0.3785 - acc: 0.8395
Epoch 49/55
8000/8000 [==============================] - 1s 126us/step - loss: 0.3774 - acc: 0.8396
Epoch 50/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.3758 - acc: 0.8399
Epoch 51/55
8000/8000 [==============================] - 1s 154us/step - loss: 0.3751 - acc: 0.8410
Epoch 52/55
8000/8000 [==============================] - 1s 152us/step - loss: 0.3739 - acc: 0.8400
Epoch 53/55
8000/8000 [==============================] - 1s 157us/step - loss: 0.3726 - acc: 0.8413
Epoch 54/55
8000/8000 [==============================] - 1s 159us/step - loss: 0.3706 - acc: 0.8430
Epoch 55/55
8000/8000 [==============================] - 1s 157us/step - loss: 0.3672 - acc: 0.8429

AttributeError: 'StandardScaler' object has no attribute 'values'

In [454]:
classifier.predict(X_test)

array([[0.05228662],
       [0.15278786],
       [0.14449745],
       ...,
       [0.05920535],
       [0.05272087],
       [0.05465016]], dtype=float32)

In [458]:
t.shape

(3000, 1)

In [455]:
t=t>0.5

In [456]:
t

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [459]:
y_test.shape

(2000,)

In [276]:
pred=[]
for i in range(3000):
    k=t[i]
    pred.append(k)

In [277]:
pred.unique

AttributeError: 'list' object has no attribute 'unique'

In [278]:
pred

[array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),

In [461]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(t[0:2000],y_test)

In [462]:
cf

array([[1588,  412],
       [   0,    0]], dtype=int64)